title: Gérard D'Alto - Data Analyst Portfolio
email: gerard.dalto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio de Gérard D'Alto, Analyste de données sociales. Découverte de mes projets, analyses, compétences et visualisations graphiques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gerardinho31.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: Gerardinho31

# Build settings
theme: minima # Using the default Jekyll minima theme as a convenient starting point
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfile/
  - gemfile.lock/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Add collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:path/
